### ISSUE TITLE
Error when deobfuscating some files

### ISSUE THREAD

**Issue by nicepot** [j4k0xb/webcrack#102]
### Describe the bug

Error when deobfuscating some files

### Expected Behaviour

Debofus
[a.txt](https://github.com/user-attachments/files/16551090/a.txt)

### Code

```JavaScript
see attachment
```

**Comment by j4k0xb** [comment]
Another obfuscator injected invalid code like `_0x2c1033()+=_0x18f210`.
This is never executed but the parser complained, now it can recover from such errors and obfuscator.io is successfully deobfuscated.

But you'll have to find a different way/tool to deal with the `$1`
```js
if ($1[5762] !== $1[5762]) {
        if (_0x263127 && !_0x350490) {
          (0, _0x208788[$1[6070]])(_0x1af268, _0x1afdd7);
          return () => {
            (0, _0x3825b7[$1[6070]])(_0xfd8ea3, null);
          };
        }
      } else {
        _0x1b25b0[$1[1771]](_0x39476d, {
          [$1[6070]]: () => _0x13e75d
        });
```

**Comment by nicepot** [comment]
@j4k0xb couldnt u add ignoring invalid code?

**Comment by j4k0xb** [comment]
Wdym? I just added that in https://github.com/j4k0xb/webcrack/commit/241f9469e6401f3dabc6373233d85a5e76966b54
