### ISSUE TITLE
cannot deobfuscate

### ISSUE THREAD

**Issue by manojdjoshi** [j4k0xb/webcrack#103]
### Describe the bug

cannot deobfuscate this type code

### Expected Behaviour

how to deobfuscate this type file

### Code

```JavaScript
https://drive.google.com/file/d/1Bom9u3d2XUk0iuZtK2Z9iFbxtqz6XETn/view?usp=sharing
```

**Comment by j4k0xb** [comment]
The file is corrupted:
![image](https://github.com/user-attachments/assets/16203503-d4db-40c0-9449-bfeabca9dad2)

```js
eval((function (�, �, �, Z, �, �) {
� = function (�) {
return � < � ? "" : �(parseInt(� / �)) + (� = � % �) > 35 ? String.fromCharCode(� + 29) : �.toString(36);
};
if (!"".replace(/^/, String)) { 
while (�--) {
�[�(�)] = (Z[�]) || (�(�));
}
Z = [function (�) {
return �[�];
}];
� = function () {
return "\\w+";
};
� = 1;
}
while (�--) {
if (Z[�]) { 
� = �.replace(new RegExp("\\b" + �(�) + "\\b", "g"), Z[�]);
}
}
return �;
})("b 9L=[
```
For these lines you can get the source as explained in https://www.trickster.dev/post/understanding-javascript-packers


Also webcrack only supports newer https://github.com/javascript-obfuscator/javascript-obfuscator versions, you probably need to search for another tool
