### ISSUE TITLE
Support for jsconfuser

### ISSUE THREAD

**Issue by nostopgmaming17** [j4k0xb/webcrack#110]
[JS Confuser](https://js-confuser.com/) is a new unknown obfuscator which isnt able to be deobfuscated
also support for [js defender preemptive](https://jsd-online-demo.preemptive.com/) obfuscator since it doesnt work that well either

**Comment by j4k0xb** [comment]
not planned, js-confuser is getting updated regularly and jsdefender is paid + closed source

**Comment by Murka007** [comment]
I think it is worth to have at least some basic support, because a lot of people are switching to other obfuscators or making their own version of it. Those that this tool is not capable to handle.

**Comment by 0xdevalias** [comment]
> Those that this tool is not capable to handle.

@Murka007 I haven't looked into how feature complete it is, but I know that @j4k0xb was doing some work a while back on a plugin system to help support people implementing features that weren't really common enough to fit into 'core'; which could be a way for the community to help build out that sort of functionality for other obfuscators if there is the desire there for it.

> Sounds like a good idea but imo it would be better to support this kind of library/script specific stuff by writing your own babel plugins and passing them webcrack, which also makes it reusable in other projects that use babel.
> 
> Otherwise it's hard to draw a line for which ones are baked in and which ones aren't. 
>
> _Originally posted by @j4k0xb in https://github.com/j4k0xb/webcrack/issues/143#issuecomment-2692345330_

These might point you in the right direction:

- https://github.com/j4k0xb/webcrack/issues/48
  - https://github.com/j4k0xb/webcrack/pull/51
- https://webcrack.netlify.app/docs/guide/api.html#plugins
  - https://webcrack.netlify.app/docs/guide/api.html#using-babel-plugins
    - https://babeljs.io/docs/plugins
      - https://babeljs.io/docs/plugins#plugin-development
    - https://github.com/jamiebuilds/babel-handbook/blob/master/translations/en/plugin-handbook.md

And you can see some further (older) discussion around this in the comments from this onwards:

- https://github.com/j4k0xb/webcrack/issues/143#issuecomment-2692517232
