### ISSUE TITLE
Tokenization is skipped for long lines for performance reasons.

### ISSUE THREAD

**Issue by NextGenerationHackers** [j4k0xb/webcrack#114]
### Describe the bug

Tokenization is skipped for long lines for performance reasons. This can be configured via editor.maxTokenizationLineLength.

and

Rendering paused for long line for performance reasons. This can be configured via editor.stopRenderingLineAfter.

![image](https://github.com/user-attachments/assets/ac04cbdf-4457-4a56-aa45-0055ad81bce2)

### Expected Behaviour

Decode this File: https://raw.githubusercontent.com/GoogleNight/kixeye.com/79fda15cd1a5d63cb6bee5cec8cb21db99245e5e/66e22ee0-199d.js

### Code

```JavaScript
https://raw.githubusercontent.com/GoogleNight/kixeye.com/79fda15cd1a5d63cb6bee5cec8cb21db99245e5e/66e22ee0-199d.js
```

### Logs

```Text
Tokenization is skipped for long lines for performance reasons. This can be configured via editor.maxTokenizationLineLength.

And: 

Rendering paused for long line for performance reasons. This can be configured via editor.stopRenderingLineAfter.
```

**Comment by j4k0xb** [comment]
damn that script is 37 MB
you might have more luck with the CLI and these flags: https://webcrack.netlify.app/docs/guide/common-errors.html#heap-out-of-memory
