### ISSUE TITLE
BABEL_PARSER_SYNTAX_ERROR / REASONCODE: UNEXPECTEDTOKEN

### ISSUE THREAD

**Issue by NextGenerationHackers** [j4k0xb/webcrack#116]
### Describe the bug

![image](https://github.com/user-attachments/assets/b13919ac-bacc-417a-8b80-95175af58b5a)

### Expected Behaviour

To Start the Process

### Code

```JavaScript
https://raw.githubusercontent.com/NextGenerationHackers/WCJSDECODER/refs/heads/main/Game%20Files/Decoded%20Game%20File%20V1/VIPDecoded.js
```

**Comment by j4k0xb** [comment]
it is invalid syntax, there are many `? . ` in the script
```js
[__w9_L3y[_0xd0709e(0x1b0)]]] ? . [__w9_L3y[_0xd0709e(0x18e)]]
```
