### ISSUE TITLE
Loss of Unused String Arrays in Webcrack Processed Code

### ISSUE THREAD

**Issue by as13579e** [j4k0xb/webcrack#118]
### Describe the bug

Description:
When processing code using Webcrack, if the code contains unused string arrays, these arrays are missing in the processed output. For example, when processing the following code on https://webcrack.netlify.app/:
`var temp = ["abc", "efv"];`
The string array is lost in the decompiled code. Please address this issue as soon as possible to prevent such loss in future processing.

### Expected Behaviour

When processing code that includes unused string arrays with Webcrack, the arrays should be retained in the output even if they are not used in the code logic.

### Code

```JavaScript
var temp = ["abc", "efv"];
```

**Comment by j4k0xb** [comment]
It's a side effect of trying to inline these string arrays (old obfuscator version)
Sure I could keep it, but what's the point if it's not referenced?

**Comment by as13579e** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by as13579e** [comment]
> It's a side effect of trying to inline these string arrays (old obfuscator version) Sure I could keep it, but what's the point if it's not referenced?


你的回复可以这样翻译成英文：

I encountered a use case where I need to decompile a large file (over 100,000 lines of code). Compiling all 100,000 lines at once with Webcrack is nearly impossible, so I need to split it into several code blocks, compile each block with Webcrack, and then piece them back together. The unused string arrays might be referenced in other code blocks, so they need to be retained. In future updates, could you provide an option to keep these arrays?

**Comment by as13579e** [comment]
> It's a side effect of trying to inline these string arrays (old obfuscator version) Sure I could keep it, but what's the point if it's not referenced?
I encountered a use case where I need to decompile a large file (over 100,000 lines of code). Compiling all 100,000 lines at once with Webcrack is nearly impossible, so I need to split it into several code blocks, compile each block with Webcrack, and then piece them back together. The unused string arrays might be referenced in other code blocks, so they need to be retained. In future updates, could you provide an option to keep these arrays?

**Comment by as13579e** [comment]
> It's a side effect of trying to inline these string arrays (old obfuscator version) Sure I could keep it, but what's the point if it's not referenced?

I encountered a use case where I need to decompile a large file (over 100,000 lines of code). Compiling all 100,000 lines at once with Webcrack is nearly impossible, so I need to split it into several code blocks, compile each block with Webcrack, and then piece them back together. The unused string arrays might be referenced in other code blocks, so they need to be retained. In future updates, could you provide an option to keep these arrays?

**Comment by j4k0xb** [comment]
> Compiling all 100,000 lines at once with Webcrack is nearly impossible

It's designed to handle large files in a reasonable time (37Mb js needs about 5GB memory and 2 minutes on my CPU).
Using the CLI without unpacking/jsx/mangling can also speed it up, so I suggest trying that first.
If it still doesn't work for some reason then that should be fixed instead.

> so I need to split it into several code blocks, compile each block with Webcrack, and then piece them back together

Not recommended, there are a bunch of other modifications that only work correctly when analyzing the whole file...

> In future updates, could you provide an option to keep these arrays?

It keeps unused arrays by default now (in the playground, not published to npm yet), but generally the goal is to not require configs/options.

**Comment by as13579e** [comment]
Thank you for fixing this issue.
