### ISSUE TITLE
Make It Possible to Collapse Arrays

### ISSUE THREAD

**Issue by JonJon565** [j4k0xb/webcrack#124]
Currently, it is not possible to collapse arrays which if you can a bunch of objects in an array it gets annoying
![image](https://github.com/user-attachments/assets/86fae15d-59fc-4595-96ec-fac3dc648b8a)
VSCode does have support for this
![image](https://github.com/user-attachments/assets/34ade200-1960-4b4e-89fc-f3f21a46b1f9)
Example Code:
`var e = "";
var p = [{
  p: "",
  w: 0,
  z: 2
}, {
  p: "",
  w: 0,
  z: 2
}, {
  p: "",
  w: 0,
  z: 2
}, {
  p: "",
  w: 0,
  z: 2
}];`

**Comment by j4k0xb** [comment]
> Folding ranges are either computed by semantic language servers or are computed by the editor based on indentation, in a programming language agnostic way.
> 
> In the Monaco Editor, the JS/TS language support does not contribute a folding range provider, so the folding ranges are computed based on indentation.

 _Originally posted by alexdima in [#1847](https://github.com/microsoft/monaco-editor/issues/1847#issuecomment-591652431)_

So it's a limitation of monaco-editor, can't implement unfortunately.
