### ISSUE TITLE
Using BabelJS to convert Obfuscated JS to AST, then AST to JS

### ISSUE THREAD

**Issue by GunGunGun** [j4k0xb/webcrack#125]
steakenthusiast made a guide for using BabelJS for deobfuscating any type of obfuscation: https://steakenthusiast.github.io/

This method is pretty absolute, they make use of BabelJS to AST the code, then convert back to the readable JS code.

Not sure if this can be implemented as a feature of webcrack.

**Comment by j4k0xb** [comment]
that's already how it works ^^
