### ISSUE TITLE
Base64 Obfuscation that doesn't seem to be deobfuscable

### ISSUE THREAD

**Issue by GunGunGun** [j4k0xb/webcrack#127]
I tried to recover it with all the current deobfuscators and it doesn't seem to be possible, 

Link: https://pastebin.com/DwyrBtrg

Webcrack is outputting something pretty unreadable too, even worse than just beatify it only.

**Comment by j4k0xb** [comment]
should be a pretty simple fix, it also needs to detect arrow functions instead of only normal ones
that's the function that rotates the string array:
```js
(n => {
  var W = _0x382f;
  var r = _0x37c9;
  var c = _0x57ce();
  for (; true;) {
    try {
      if (parseInt(r(725, "]O8Y")) / 1 * (-parseInt(W(776)) / 2) + -parseInt(W(797)) / 3 + -parseInt(W(693)) / 4 + -parseInt(W(761)) / 5 * (parseInt(W(502)) / 6) + -parseInt(W(790)) / 7 + parseInt(W(727)) / 8 + parseInt(W(611)) / 9 * (parseInt(W(682)) / 10) == n) {
        break;
      }
      c.push(c.shift());
    } catch (n) {
      c.push(c.shift());
    }
  }
})(356672);
```

**Comment by GunGunGun** [comment]
I think by far this is the most headache obfuscation I've dealt with. I also don't know the origins of it, but I've seen this type of obfuscator more and more often, it's getting adapted by manga/anime/adult websites.

If it's opensource then we can do a lot to measure the potential of this type of code obfuscation.

**Comment by GunGunGun** [comment]
Thank you very much, it works flawlessly now!
