### ISSUE TITLE
some new obfuscator

### ISSUE THREAD

**Issue by kzorin52** [j4k0xb/webcrack#14]
maybe obfuscator.io update, idk. this code looks weird and dont deobfuscating in webcrack:
[obfs.txt](https://github.com/j4k0xb/webcrack/files/12378411/obfs.txt)

**Comment by j4k0xb** [comment]
You'd have to find some other deobfuscator for https://github.com/MichaelXF/js-confuser first (no plan on creating one at the moment)

Only afterwards the obfuscator.io layer can be deobfuscated
