### ISSUE TITLE
unexpected token

### ISSUE THREAD

**Issue by BotSolver** [j4k0xb/webcrack#15]
### Describe the bug

![image](https://github.com/j4k0xb/webcrack/assets/73006302/e314d02f-e460-4af8-bf37-a03e3599d3e9)
basically that

### Expected Behaviour

for it do just deobfuscate I guess?

### Code

```JavaScript
https://raw.githubusercontent.com/BotSolver/krunk/main/game_1_4.js
```

### Logs

```Text
no logs, used site.
```

**Comment by j4k0xb** [comment]
That script is incomplete, should be like 10x bigger and end with `;}]));`
![image](https://github.com/j4k0xb/webcrack/assets/55899582/948afc2d-5a34-4c96-a7a7-dbf5e53e4137)

if you got it from the chrome console, try right click -> save... copying sometimes cuts it off iirc
