### ISSUE TITLE
I just need help, it's removing a defined value from this code.

### ISSUE THREAD

**Issue by BotSolver** [j4k0xb/webcrack#16]
### Describe the bug

I press deobfuscate and everything is fine, but if I put the code with the rest of the files it says this

background-wrapper.js:1 ReferenceError: _0x541988 is not defined
    at Object.S (background.bundle.js:1:152)
    at new It (background.bundle.js:1:338930)
    at background.bundle.js:1:930915
    at background.bundle.js:1:930940
    at background.bundle.js:1:931274
    at background.bundle.js:1:934771
    at background.bundle.js:1:934775

I don't mean to be annoying if anything so I apologize, just trying to get something done

### Expected Behaviour

I expect to keep the value defined but it seems to remove it, breaking the whole code for the check

### Code

```JavaScript
https://cdn.discordapp.com/attachments/1139534194402414592/1142290059559714816/0mY0xmK.js
```

### Logs

```Text
background-wrapper.js:1 ReferenceError: _0x541988 is not defined
    at Object.S (background.bundle.js:1:152)
    at new It (background.bundle.js:1:338930)
    at background.bundle.js:1:930915
    at background.bundle.js:1:930940
    at background.bundle.js:1:931274
    at background.bundle.js:1:934771
    at background.bundle.js:1:934775
    at background-wrapper.js:1:5
```

**Comment by BotSolver** [comment]
since the code is obfuscated, I have no clue how it's supposed to be defined at base, so it's not something I can fix on my own.

**Comment by j4k0xb** [comment]
thanks for reporting, its an issue where `_0x541988` is accidentally detected as a proxy/wrapper function and removed
```js
function _0x541988() {
  var _0x3ad03a = a3_0x11e7;
  return _0x3ad03a(0x59b);
}
_0x15c3bf["d"](_0x314587, { S: () => _0x541988, n: () => _0x4d923d });
```

as a workaround you could manually replace it with this for now:
```js
function _0x541988() {
  return "npm";
}
```

**Comment by BotSolver** [comment]
I see, thank you

**Comment by j4k0xb** [comment]
fixed in https://github.com/j4k0xb/webcrack/releases/tag/v2.9.0
