### ISSUE TITLE
true it could result in more performance (except python lol) but afaik these languages don't have similar libs as I'm currently using (babel, isolated-vm, codemod matcher), and implementing them from scratch would be too much effort to be worth it

### ISSUE THREAD

**Issue by moongazer07** [j4k0xb/webcrack#23]
true it could result in more performance (except python lol) but afaik these languages don't have similar libs as I'm currently using (babel, isolated-vm, codemod matcher), and implementing them from scratch would be too much effort to be worth it

swc is probably the closest thing to babel but still too limited:
- "Upward traversal is not supported by swc": https://swc.rs/docs/plugin/ecmascript/cheatsheet#pathfind
- https://github.com/swc-project/swc/discussions/6576
webcrack relies heavily on this kind of stuff

_Originally posted by @j4k0xb in https://github.com/j4k0xb/webcrack/issues/22#issuecomment-1803577842_
            you could also transpile the libs if possible

**Comment by j4k0xb** [comment]
There are some js to c/wasm transpilers but:
- they only supports a small subset of js
- https://stackoverflow.com/a/5193132/4011614
  > Very, very tricky --- Javascript is a heavily dynamic language where pretty much everything can be changed at run time: object properties, functions, types, etc.
  > As such it maps very badly onto C. Any Javascript translator would have to be able to cope with such things, which means it would have to translate the Javascript into machine code at run-time - which makes it a JIT, which we're already using.

So a transpiler that supported every js feature would still be slower overall.

https://www.assemblyscript.org is very similar to js/ts but would also require rewriting or substantially modifying all libs, in which case using another language is most likely a better choice
