### ISSUE TITLE
ERR_DLOPEN_FAILED

### ISSUE THREAD

**Issue by gokaybiz** [j4k0xb/webcrack#32]
Nevermind. The issue is related with isolated-vm. I'm leaving a link in case anyone has a similar problem. https://github.com/laverdet/isolated-vm/issues/249#issuecomment-1683714551

### Describe the bug

Probably referring to __DECODE_0__ function that won't exists.

### Expected Behaviour

It should have kept the string decoder function (which should be renamed to __DECODE_0__). But somehow it removes it (I guess).

### Code

```JavaScript
```

### Logs

```Text
node:internal/modules/cjs/loader:1473
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /home/io/.local/share/pnpm/global/5/.pnpm/isolated-vm@4.6.0/node_modules/isolated-vm/out/isolated_vm.node: undefined 
symbol: _ZNK2v815ValueSerializer8Delegate20SupportsSharedValuesEv
    at Module._extensions..node (node:internal/modules/cjs/loader:1473:18)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/home/io/.local/share/pnpm/global/5/.pnpm/isolated-vm@4.6.0/node_modules/isolated-vm/isolated-vm.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v20.10.0
```

**Comment by gokaybiz** [comment]
```
node: ../src/lib/suspend.h:32: ivm::thread_suspend_handle::initialize::initialize(): Assertion `sigaction(SIGRTMIN, &handler, nullptr) == 0' failed.
[1]    24188 abort (core dumped)  webcrack base.js
```
Another log with different nodejs version.

**Comment by j4k0xb** [comment]
The `__DECODE_0__` calls couldn't be resolved because it's most likely a custom/forked obfuscator version that creates additional variables: 
![image](https://github.com/j4k0xb/webcrack/assets/55899582/0da5df97-50a7-4f7a-a328-af57d504da2d)

**Comment by gokaybiz** [comment]
So instead of ArrayExpression, we should call FunctionDeclarator and then look for multiple VariableDeclarators with integers.
And in the ExpressionStatements of the function, we should invoke calees with variable values. Right?

**Comment by j4k0xb** [comment]
For now you can manually fix it by pasting the code in the top left panel: https://astexplorer.net/#/gist/d93c015f2728aa0d0c9a7ed4359c6940
and then use the output script (bottom right panel) in webcrack

I'm working on a more general way of inlining variables, object properties etc like in https://github.com/javascript-obfuscator/javascript-obfuscator#stringarraycallstransform

**Comment by j4k0xb** [comment]
It is now being properly deobfuscated in the playground, and the npm package will probably be updated in the next few days

**Comment by gokaybiz** [comment]
@j4k0xb, thank you for your quick action
I was experimenting on ast parsing but it wasn't successful enough :)
```
export default function (babel) {
const {types: t} = babel;

  return {
    name: "ast-transform",
    visitor: {
      VariableDeclarator(path) {
        const { name } = path.node.id;
        const binding = path.scope.getBinding(name);

        if (!binding || !binding.constant) {
          return;
        }

        const initPath = path.get('init');
        if (!initPath.isExpression() || !initPath.isLiteral()) {
          return;
        }

        const replacement = t.expressionStatement(initPath.node);
        binding.referencePaths.forEach(ref => {
              ref.replaceWith(replacement);
        });
        path.remove();

      },
      AssignmentExpression(path) {
  		if (!path.node || !path.node.right) {
          return;
        }
        const { left, right } = path.node;
 
        if (t.isIdentifier(left) && t.isExpression(right) && t.isLiteral(right)) {
          const binding = path.scope.getBinding(left.name);
			console.log("AssignmentExpression -", left, right);
          const isForOrWhileOrIf = path.findParent(p =>
            p.isForStatement() || p.isWhileStatement() || p.isIfStatement()
          );

          if (binding && !binding.constant && binding.kind && binding.kind === 'var' && !isForOrWhileOrIf) {
            const replacement = t.expressionStatement(right);
            binding.referencePaths.forEach(ref => {
              ref.replaceWith(replacement);
            });
            path.remove();
          }
        }
      },
    },
  };
}
```

**Comment by gokaybiz** [comment]
it still misses ```(h = 323, v = 502, d = Xe, d(502) + d(h) ? d(v) + d(h) : "null")``` like assignments

**Comment by j4k0xb** [comment]
Should work now. Can you test if anything else is missing in https://deploy-preview-36--webcrack.netlify.app/ ?

**Comment by gokaybiz** [comment]
As far as i saw, it's working as expected right now.
Thanks for your all efforts, again.
