### ISSUE TITLE
support GopherJS bundles

### ISSUE THREAD

**Issue by 0xdevalias** [j4k0xb/webcrack#39]
- https://github.com/gopherjs/gopherjs
  - > A compiler from Go to JavaScript for running Go code in a browser
  - https://gopherjs.github.io/playground/
- https://vik0t0r.github.io/posts/Gopherjs-reverse-engineering/
  - > Gopherjs reverse engineering
    > Gopherjs is a compiler for the go language which compiles to pure javascript, it can be used to write go code which is executed on a webrowser, or where I found it, on a cordova app, while I was trying to reverse engineer an android apk. 
  - https://vik0t0r.github.io/posts/Gopherjs-reverse-engineering/#second-approach-analyzing-the-minified-code-structure
    - > At a glance, we can get the following info:
      >
      > 1.  First six lines, I will call it "header", it the same for all the projects, so we can ignore them, the only useful info is the go version, which also tell us the gopherjs version as they are linked.
      > 2.  Then we have a variable number of lines, were each line is a go package, we will split each of this lines in an individual file, so the IDE those not implode (which is what happens when you try to beautify the code all at once).
      > 3.  Lastly, we have 9 lines which are all the same for all the programs too, this is where everything starts whith the call to init(), but we will ignore this part for now.
  - https://vik0t0r.github.io/posts/Gopherjs-reverse-engineering/#vscode-extension
    - > To help with the decompiling process I will be writting a VScode extension which can be found here.
      - https://github.com/vik0t0r/gopherjsre
        - > gopherjsRE is an attempt to make analysis of gopherjs produced files easier
        - https://github.com/vik0t0r/gopherjsre/blob/master/extension.js
        - https://github.com/vik0t0r/gopherjsre/blob/master/utils.js
  - https://vik0t0r.github.io/posts/Gopherjs-reverse-engineering/#renaming-package-symbols
  - https://vik0t0r.github.io/posts/Gopherjs-reverse-engineering/#renaiming-types-in-each-package
  - https://vik0t0r.github.io/posts/Gopherjs-reverse-engineering/#renaiming-functions
  - https://vik0t0r.github.io/posts/Gopherjs-reverse-engineering/#remove-goroutines-boilerplate
  - https://vik0t0r.github.io/posts/Gopherjs-reverse-engineering/#some-ideas-for-the-future
    - > Some ideas for the future
      > Use a parser like [this one](https://github.com/acornjs/acorn/tree/master) to improve the decompiler extension. Or maybe run the code for its decompilation, as the `$packages` structure might contain really useful information, and maybe could be use for better reverse engineering.
  - Originally linked from https://gist.github.com/alexander-hanel/59af86b0154df44a2c9cebfba4996073?permalink_comment_id=4805421#gistcomment-4805421

cc // @vik0t0r FYI

## See Also

- https://github.com/pionxzh/wakaru/issues/92
- https://github.com/vik0t0r/gopherjsre/issues/1

**Comment by j4k0xb** [comment]
cool project 👍🏻
but this feels like a lot of work for a very niche feature, and is better suited to be in https://github.com/vik0t0r/gopherjsre rather than this repo
I'd rather focus on improving the current core features for now

**Comment by 0xdevalias** [comment]
> this feels like a lot of work for a very niche feature

> I'd rather focus on improving the current core features for now

@j4k0xb _nods_, that's fair enough.
