### ISSUE TITLE
Cannot move to file clicked in playground

### ISSUE THREAD

**Issue by pionxzh** [j4k0xb/webcrack#40]
### Describe the bug

When I tried playing with the playground, it successfully generated some modules. But when I clicked on files on the left panel, the playground failed to navigate / open the file. I got stuck on the input file.

System: Windows 11
Browser: Chrome 120.0.6099.129

### Expected Behaviour

Can click and see the generated file.

### Code

```JavaScript
NA
```

### Logs

![image](https://github.com/j4k0xb/webcrack/assets/9910706/ca14337d-befc-4bf6-a3f6-6ad133cf76e0)

**Comment by j4k0xb** [comment]
Hmm weird, I've only tested on Linux so far, but the path polyfill and browsers in general should never use backslashes in urls/paths 🤔
Gonna look into it

**Comment by j4k0xb** [comment]
Should work now
monaco-editor used different path formats for windows user-agents

**Comment by pionxzh** [comment]
It works now, Thanks!
