### ISSUE TITLE
Migrate to `verbatimModuleSyntax` in TypeScript config

### ISSUE THREAD

**Issue by mochaaP** [j4k0xb/webcrack#43]
As the title suggests. It should be an easy fix, since the only thing left is to mark type only imports with ESLint.

**Comment by j4k0xb** [comment]
What benefits does this have? Afaik it only affects emitting js with `tsc`, but esbuild is used for that instead

**Comment by mochaaP** [comment]
I'm using untranspiled .ts files directly from this repo (to access unexported symbols), and tsc emit errors since I enabled that option.

**Comment by j4k0xb** [comment]
Done 👍🏻 
But in the future I think it would be better to export the symbols instead of relying on the raw .ts files (could have breaking changes at any time)
Do you need specific ones? https://github.com/HarukaKinen/delance isn't available anymore

**Comment by mochaaP** [comment]
> Do you need specific ones? [redacted] isn't available anymore

I migrated that to <https://sr.ht/~self>. :)
