### ISSUE TITLE
Duplicated variable initialization when unminifying

### ISSUE THREAD

**Issue by mobapedia** [j4k0xb/webcrack#54]
Any variables initialized inside a for loop inside an inline if statement will be duplicated when unminifying.

for example:
```js
if (1) for (a=1,b=2,c=3;a<10;a++){}
```

will turn into:
```js
if (1) {
  a = 1;
  b = 2;
  c = 3;
  a = 1;
  b = 2;
  c = 3;
  for (; a < 10; a++) {}
}
```

**Comment by j4k0xb** [comment]
Nice catch 👍🏻
Fixed in https://github.com/j4k0xb/webcrack/commit/2d889c69be4f81f223d369f3e1c28720f932503c (playground is already updated, npm release will follow soon)
