### ISSUE TITLE
How to build webcrack for web browser using tools like esbuild

### ISSUE THREAD

**Issue by Sofie99** [j4k0xb/webcrack#56]
is there any guide for that? thx

**Comment by j4k0xb** [comment]
Yes you can look in the previous repo how it was done: https://github.com/j4k0xb/webcrack-ui/blob/master/esbuild.config.js
When using deobfuscation it needs a custom sandbox implementation like quickjs-emscripten or sandybox
And running it in a web worker is a bit of a mess but avoids freezing the UI
