### ISSUE TITLE
Support for Vercel

### ISSUE THREAD

**Issue by AmarnathCJD** [j4k0xb/webcrack#60]
Error [ERR_REQUIRE_ESM]: require() of ES Module /var/task/node_modules/webcrack/dist/index.js from /var/task/api/unobf.js not supported.
Instead change the require of index.js in /var/task/api/unobf.js to a dynamic import() which is available in all CommonJS modules.

**Comment by j4k0xb** [comment]
see https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
