### ISSUE TITLE
__DECODE_0__

### ISSUE THREAD

**Issue by funmolde** [j4k0xb/webcrack#67]
### Describe the bug

Hello -_- 

The javascript code is not completely __DECODE_0__ ; 

I use the online version webcrack.netlify.app

Is there a difference between the online version and the version Command Line Interface ?
Can you correct the __DECODE_0__ error?
 
Edge chromiun last version 
Windows 11 64 bit system, 24 ram

[obfuscate.txt](https://github.com/j4k0xb/webcrack/files/14626036/obfuscate.txt)
[Deobfuscate.txt](https://github.com/j4k0xb/webcrack/files/14626035/Deobfuscate.txt)
![console log](https://github.com/j4k0xb/webcrack/assets/13144261/49c05181-375e-4cf6-b789-2303a2f27429)

Thank you for your help -__-

### Expected Behaviour

 __DECODE_0__

### Code

```JavaScript
small party example:
const originalQuerySelector = document[__DECODE_0__("0x245" - {
  e: 102
}.e, "e8^^") + __DECODE_0__("0x289" - {
  e: 102
}.e, "e8^^")];
document[__DECODE_0__("0x25a" - {
  e: 102
}.e, "6lfy") + __DECODE_0__("0x261" - {
  e: 102
```

**Comment by j4k0xb** [comment]
Seems like the only reason it failed is because of
```js
function G(a, b) {
  return d(b - { e: 102 }.e, a);
}
```
Try simplifying it to this for now, then deobfuscate. I'll also work on doing that automatically
```js
function G(a, b) {
  return d(b - 102, a);
}
```

Result:
```js
function flybpass(a) {
  if (("" + a).includes("goShortlink") || ("" + a).includes(".g-recaptcha") || ("" + a).includes("go-link")) {
    window.location.assign("/bypass.html");
  }
  return originalQuerySelector.call(document, a);
}
const originalQuerySelector = document.querySelector;
document.querySelector = flybpass;
```

> Is there a difference between the online version and the version Command Line Interface ?

not much, the online version always uses the latest commit and CLI is published later

**Comment by funmolde** [comment]
> ```js
> function G(a, b) {
>   return d(b - 102, a);
> }
> ```

Thank you very much, it works  -___-
