### ISSUE TITLE
`Ctrl` + `S` doesn't trigger 'download the code' in web IDE as per the docs

### ISSUE THREAD

**Issue by 0xdevalias** [j4k0xb/webcrack#81]
### Describe the bug

The docs suggest that `Ctrl` + `S` will trigger 'download the code':

- https://webcrack.netlify.app/docs/guide/web.html

Yet when I try that, it doesn't seem to do anything. I'm on macOS, so the default/equivalent would usually be `Cmd` + `S`; but that just triggers the browser's default 'save this page' feature.

### Expected Behaviour

Pressing `Ctrl` + `S` would trigger downloading the code as per the docs; or alternatively, the docs are updated to represent how to do this properly.

### Code

```JavaScript
N/A
```

### Logs

```Text
N/A
```

**Comment by 0xdevalias** [comment]
When searching `keybinding`, I don't see any references that seem to align with this `Ctrl`+`S`:

- https://github.com/search?q=repo%3Aj4k0xb%2Fwebcrack+keybinding&type=code

**Comment by j4k0xb** [comment]
Hmm got lost during the monorepo/ide PR, here it was:

https://github.com/j4k0xb/webcrack-ui/blob/e8dc1b43b138c759cc206db240e387bf4628665e/src/editor.ts#L116-L120

**Comment by 0xdevalias** [comment]
> now it's back

@j4k0xb Awesome, thankyou! :)
