### ISSUE TITLE
Download deobfuscated, file directly with a button

### ISSUE THREAD

**Issue by h9nt** [j4k0xb/webcrack#85]
Its would be a good idea to make after deobfuscated, a button to download the file

**Comment by j4k0xb** [comment]
That's being worked on in #79 
![image](https://github.com/j4k0xb/webcrack/assets/55899582/ed6c7fd9-60c6-4923-a95a-6d451a105801)

**Comment by h9nt** [comment]
> That's being worked on in #79 ![image](https://private-user-images.githubusercontent.com/55899582/335163063-ed6c7fd9-60c6-4923-a95a-6d451a105801.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczNjUwMTEsIm5iZiI6MTcxNzM2NDcxMSwicGF0aCI6Ii81NTg5OTU4Mi8zMzUxNjMwNjMtZWQ2YzdmZDktNjBjNi00OTIzLWE5NWEtNmQ0NTFhMTA1ODAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDIxNDUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxNTlkYWI0ODA0MzIwMmYwOTE0OGQ5YTk4ZTBiMGMzOGI4ZGU4YjIwMTkyZTc4NmQ5YzI0ZDJkNzZjNWM1YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YJz2L1t3bE7qfjxUklHBO748Mc_ZJP63w7e7UCYqLhc)

Is this the web version or why i can't see it?

**Comment by j4k0xb** [comment]
You mean the screenshot? idk

**Comment by h9nt** [comment]
> You mean the screenshot? idk

Allright 😂
