### ISSUE TITLE
*lint menu* can have multiple dropped down

### ISSUE THREAD

**Issue by joskezelensky** [j4k0xb/webcrack#88]
### Describe the bug

instead of allowing only 1 dropdown, (for example file or settings), they can have both dropped down	 

### Expected Behaviour

1 dropped down (at a time), never two at the same time

### Code

```JavaScript
/
```

### Logs

```Text
/
```

**Comment by j4k0xb** [comment]
Fixed, now it also closes when clicking on a sub-menu (open file) or outside

**Comment by joskezelensky** [comment]
wow thanks that was fixed really fast!
