### ISSUE TITLE
broken tab style

### ISSUE THREAD

**Issue by pionxzh** [j4k0xb/webcrack#89]
### Describe the bug

<img width="274" alt="image" src="https://github.com/j4k0xb/webcrack/assets/9910706/8b76a185-a79b-4435-9057-2a30b04247bc">

### Expected Behaviour

<img width="233" alt="image" src="https://github.com/j4k0xb/webcrack/assets/9910706/2a971713-84a8-4918-a91b-44176b3dd240">

### Code

```JavaScript
N/A
```

**Comment by j4k0xb** [comment]
Fixed:
![image](https://github.com/j4k0xb/webcrack/assets/55899582/b1122924-365f-4e60-a713-b1564e3af9e0)
