### ISSUE TITLE
Web IDE 'File -> Save'/etc menu items suggest the wrong keybindings on macOS

### ISSUE THREAD

**Issue by 0xdevalias** [j4k0xb/webcrack#90]
### Describe the bug

Was just checking out the web IDE again after the following landed:

- #78 
  - #79

And noticed that the 'File' menu says to use `Ctrl+S` to save (and other similar menu items):

![image](https://github.com/j4k0xb/webcrack/assets/753891/51cf5c71-ab60-45ab-aebb-0044ba2575f1)

But this doesn't work on macOS, as the keybinding is actually `Cmd+S`:

- https://github.com/j4k0xb/webcrack/issues/81
  - https://github.com/j4k0xb/webcrack/commit/5e66a1196d1bbe30cd7a09caf00b00aa9dbd5b46#diff-68af5958cdab96c0e0d14bc33af127c4ed7e75fc1664c19b370025c43f8a6633R104

### Expected Behaviour

It would be good if the suggested key bindings in the menu were able to update themselves based on the platform's bindings.

### Code

```JavaScript
N/A
```

### Logs

```Text
N/A
```

### See Also

- https://github.com/j4k0xb/webcrack/issues/91
- https://github.com/j4k0xb/webcrack/issues/92

**Comment by 0xdevalias** [comment]
Seems the keybindings are hardcoded in the `MenuButton` component props here:

https://github.com/j4k0xb/webcrack/blob/f6df5f2c91fe5f848b9aa24dbcfa0b39b308a1e6/apps/playground/src/components/menu/Menu.tsx#L39-L64

It might be cool if they were able to read from the same constant as the keybindings themselves, to ensure they remain in sync?

https://github.com/j4k0xb/webcrack/blob/f6df5f2c91fe5f848b9aa24dbcfa0b39b308a1e6/apps/playground/src/components/MonacoEditor.tsx#L109-L127

**Comment by j4k0xb** [comment]
Doing it the same as vscode/monaco now: https://github.com/microsoft/vscode/blob/d40dff9ef9aacb8e5226bcf3938c71f4b9543120/src/vs/base/common/platform.ts#L109-L110

**Comment by 0xdevalias** [comment]
Looks good, thanks! :)
